### ISSUE TITLE
Get CPU temperature working in Netgear R6300V2 running Merlin 380.70

### ISSUE THREAD

**Issue by richardzone** [Vaskivskyi/asusrouter#101]
CPU temperature is not working on Netgear R6300V2 router running Merlin 380.70

https://github.com/Vaskivskyi/asusrouter/blob/b07d47ea5e5a61f64f530d677b82d5ceacbad62e/asusrouter/const.py#L244

^Above does not match what I have from my router's `/ajax_coretmp.asp`: 

```
curr_coreTmp_2_raw = "44&deg;C";
curr_coreTmp_2 = (curr_coreTmp_2_raw.indexOf("disabled") > 0 ? 0 : curr_coreTmp_2_raw.replace("&deg;C", ""));
curr_coreTmp_5_raw = "47&deg;C";
curr_coreTmp_5 = (curr_coreTmp_5_raw.indexOf("disabled") > 0 ? 0 : curr_coreTmp_5_raw.replace("&deg;C", ""));
curr_coreTmp_cpu = "58";
```

It's actually `curr_coreTmp_cpu` rather than `curr_cpuTemp`

I have not checked whether this applies to: (a) stock Asus, or (b) Merlin specific or (c) customization specifically made for Netgear devices. Although (c) seems highly unlikely.

Thanks for your awesome ha integration anyway!

**Comment by richardzone** [comment]
@Vaskivskyi I wonder if you have time to take a look? Let me know if any help is needed

**Comment by Vaskivskyi** [comment]
Hey, @richardzone,

First of all, I am really sorry for the late reply - I didn't see a notification about the opened issue.

Thanks for your feedback! 👍🏻 

PR #102 is adding this functionality, so it will be available in the HA integration with the next version. Either by the end of this week or next week.
